name: Update CS2Run History

on:
  schedule:
    - cron: "*/6 * * * *" # каждые 6 минут
  workflow_dispatch:
  repository_dispatch:
    types: [external_update_trigger]

jobs:
  update-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Update last_updated field in JSON
        run: |
          FILE="data/history.json"

          # Если файла нет — создаём
          if [ ! -f "$FILE" ]; then
            echo "Создаём новый $FILE"
            echo '{"last_updated": "", "stats": {"crashes": []}}' > $FILE
          fi

          # Получаем текущее время в Омске (UTC+7)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S+07:00")

          # Обновляем last_updated
          jq --arg now "$NOW" '.last_updated = $now' "$FILE" > tmp.$$.json && mv tmp.$$.json "$FILE"

          echo "✅ Обновлено время: $NOW"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "Нет изменений — пропускаем коммит"
          else
            git add data/history.json
            git commit -m "Auto-update CS2Run data [$(date)]"
            git push
          fi
