name: Update CS2Run History

on:
  schedule:
    - cron: "*/6 * * * *"  # каждые 6 минут
  workflow_dispatch:
  repository_dispatch:
    types: [external_update_trigger]

jobs:
  update-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Update history JSON
        run: |
          FILE="data/history.json"

          # Проверяем, есть ли файл
          if [ ! -f "$FILE" ]; then
            echo "Создаём новый $FILE"
            echo '{"last_updated": "", "stats": {"crashes": []}}' > $FILE
          fi

          # Получаем текущее время ISO с часовым поясом Омска
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S+07:00")

          # Обновляем last_updated в JSON
          jq --arg now "$NOW" '.last_updated = $now' "$FILE" > tmp.$$.json && mv tmp.$$.json "$FILE"

          echo "✅ last_updated обновлено на $NOW"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "Нет изменений — коммит пропущен"
          else
            git add .
            git commit -m "Auto-update CS2Run data [$(date)]"
            git push
          fi
